### PR TITLE
Replace `daemon-kit` with the `whenever` gem

### PR DESCRIPTION
**Pull request by morse255**
This PR replaces [`daemon-kit`](https://github.com/kennethkalmer/daemon-kit) with the [`whenever`](https://github.com/javan/whenever) Ruby gem. This change was made because `daemon-kit` hasn't been updated since 2018 and, we have no longer have a need to run this project as a daemon due to containerization. The `whenever` gem was a more natural fit to schedule this work because that's the solution we're using to schedule tasks inside all of our other containerized projects.

Some notable items:

* The PeopleSoft environment is now injected via a `PS_ENV` environment variable. The `script/_prod_entrypoint` script was modified to log this value so that the container will not start if the `PS_ENV` environment variable is missing.

* A new rake task called `peoplesoft_course_class_data:download_and_copy_files` was created to encapsulate both `peoplesoft_course_class_data:download` and `peoplesoft_course_class_data:copy_good_files` tasks. The `whenever` gem will run tasks in parallel if you specify multiple lines in the `config/schedule.rb`. This new tasks ensures the "download" task completes before the "copy_good_files" task is executed. [An alternative would be to use `flock`](https://github.com/javan/whenever/wiki/Exclusive-cron-task-lock-with-flock), but that strategy did not seem as readable as the new rake task.

* The `PeoplesoftCourseClassData::Config.CREDENTIALS` variable was modified because the staging identifier was incorrectly using `ent` instead of `qat`. As far as I can tell, the `ent` value was not correct and that value should always have been `qat`.

### CODE REVIEW

**Review by eeklund — APPROVED** [review]
~The removal of some of the files from this PR would remove boiler plate Rails files in addition to the DaemonKit commands. I believe Rails will load without the files present, but it might be confusing to devs that go to modify files if they aren't present. It might be good to have empty files for most of these:~
~- config/environment.rb~
~- config/environments/development.rb~
~- config/environments/test.rb~
~- config/environments/staging.rb (which inherits from production in case anything is added since staging isn't a default environment in Rails)~
~- config/environments/production.rb~

Ignore the man behind the curtain, there's nothing to see there. I assumed Rails when it is NOT a rails project. Sorry for the misdirection.

**Comment by morse255** [comment]
> The removal of some of the files from this PR would remove boiler plate Rails files in addition to the DaemonKit commands. I believe Rails will load without the files present, but it might be confusing to devs that go to modify files if they aren't present. It might be good to have empty files for most of these:
> 
> * config/environment.rb
> * config/environments/development.rb
> * config/environments/test.rb
> * config/environments/staging.rb (which inherits from production in case anything is added since staging isn't a default environment in Rails)
> * config/environments/production.rb

**Comment by morse255** [comment]
Inadvertently closed the PR while editing a comment. 🙃

**Comment by morse255** [comment]
Per our Slack conversation, this is not actually a Rails project (only uses ActiveSupport), so it probably makes sense to remove the `config/environments` contents.

**Pull request merged**
